language: python
dist: xenial
python:
  - "3.6"
# cache:
#   pip: true
before_install:
  - pip3 install -U pip
install:
  - pip3 install codecov
  - pip3 install --upgrade pip setuptools wheel
  - pip3 install codecov
  - pip3 install -r tests/requirements.txt 
  - python3 setup.py install
  - pip install coverage
script:
  - python3 tests/tests.py
after_success:
  - codecov
notifications:
  email:
  - on_failure: always
  - on_success: always