{
  "comment": {
    "layout": "header, diff, changes"
  }, 
  "coverage": {
    "range": [
      80.0, 
      100.0
    ], 
    "precision": 0
  }, 
  "codecov": {
    "archive": {
      "uploads": false
    }
  }
}